version: '2'
services:
  #CASSANDRA-DB
  cassandra:
    image: cassandra:latest
    container_name: cassandra-db
    hostname: localhost
    privileged: true
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 9042:9042
      - 9160:9160
      - 7199:7199
      - 7001:7001
      - 7000:7000
    volumes:
      # - ./data:/var/lib/cassandra/data:rw
      - ./scripts/path:/tmp/scripts:rw
    networks:
      local-network:

networks:
  local-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.101.101.0/24
        gateway: 172.101.101.1